### PR TITLE
User Interface outline for Tic Tac Toe Project

### PR DESCRIPTION
**Pull request by Abhigyan001**
- Created an outline on how to take input from and display results to the user, along with the updated board positions for the next player to make a move.

### CODE REVIEW

**Review by krys2fa — CHANGES_REQUESTED** [review]
Nicely done @Abhigyan001  👏

Your project has good commit messages and a descriptive PR. 💪

Just a few more changes to get this milestone approved. They can be seen below:

Status: Changes Required ♻️

- [x]  [REQUIRED]  In this milestone, you are required to only **mock** the basic flow of the game. No game logic or actual computations (e.g.: checking for a winner) is required.
This means the game should display prompt for users (print/puts) and collect user input (get.chomp). After each move the board should be displayed and the game should end with a win or draw message regardless of who won or not.

Please request for another review after implementing the changes.

Happy Coding 🖥️ 😃

You can contact me on slack (Chris Amanor) for any clarification.

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

Good job on mocking the game logic, but you need to at least prompt the players about various stages of the game - entering their name, asking for a token position, displaying the board each time player makes a move, etc.

You are allowed to use inline comments, but please also prompt the player in the console.

A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)). Inside the loop you can call actions repeated for each move. Also, it needs to be terminated at some point (after a winning move or draw to be more specific).

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hello @Abhigyan001 


🌟  Your flow looks great! You thought about almost all steps, just remember that gets.chom are also required to work in this milestone 

- [x] Please uncomment all the lines where you require user input with gets.chomp
- [x] About your loop, to stop it, you need to put it inside a conditional, please put the conditions to trigger the `game = false` to stop the loop (with comments is okay)

Great job until now, 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @Abhigyan001 and @krys2fa :lollipop: :balloon: 

### Thank you for working on the changes requested by the previous reviewers :medal_sports: :medal_sports:  I see most of your logic is done using comments in your code and that's okay still we are missing some requirements so let's work on them :construction: :construction_worker: :construction_worker_man: 

#### Behavior

> Even though not everything has to work (this means that you can use constant values instead of the game actually validating the player's input) the program doesn't have to break in the normal flow and it's breaking due to variables not existing.

- [ ] The game doesn't have to break at normal flow

image

#### Implementation details

> Just as requested by the previous reviewer a loop is needed for this milestone so let's work on it I see you have it with comments but it should really be present with working code 

* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x] Inside the loop, the students should call actions repeated for each move
* [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### That's it, team! :raised_hands: 

### Please :pray:  do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Review by kitpao — APPROVED** [review]
# 👋 Hi again @Abhigyan001 

Great job implementing the required changes 🌟 Everything is working fine and you have the flow 

### 👏 Your project has been approved 👏
### 🚀 You may merge to development and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Pull request merged**
